"""Execution plan data models.

These define the contract between Producer and Translator.
The Producer outputs an ExecutionPlan; the Translator consumes it.
"""

from pydantic import BaseModel, Field
from enum import Enum


class PlaytestMode(str, Enum):
    UI = "ui"           # Agent plays through browser
    ADAPTER = "adapter" # Headless batch simulation
    NONE = "none"       # No playtesting (e.g., adapter build round)


class AgentRole(str, Enum):
    DESIGNER = "designer"
    IMPLEMENTER = "implementer"
    PLAYTESTER = "playtester"


class AgentConfig(BaseModel):
    """Configuration for one agent in the dev loop."""
    role: AgentRole
    model: str = "claude-opus-4-6"
    system_context: str
    tools: list[str] = Field(default_factory=list)


class Milestone(BaseModel):
    """A checkpoint in the development process.
    
    Agents self-organize toward each milestone.
    The only hard constraint is exit_criteria — how agents get there is up to them.
    """
    id: int
    name: str
    goal: str
    exit_criteria: list[str]
    playtest_mode: PlaytestMode = PlaytestMode.UI
    adapter_hint: str | None = None  # Hint that agents may need to build an adapter
    human_review: bool = True
    max_iterations: int = 50  # Max agent turns before escalating to human


class GameConfig(BaseModel):
    """Game metadata and tech stack."""
    name: str
    genre: str
    platform: str
    stack: dict[str, str] = Field(default_factory=dict)  # e.g. {"engine": "Phaser 3", "language": "TypeScript"}


class ExecutionPlan(BaseModel):
    """The complete blueprint for building a game.
    
    Generated by the Producer from game_design.md.
    Consumed by the Translator to generate runnable multi-agent code.
    """
    game: GameConfig
    agents: dict[str, AgentConfig]  # role_name -> config
    milestones: list[Milestone]
    adapter_needed: bool = False
    adapter_reason: str | None = None
